version: '3.8'

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - api
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync


  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: ./server/requirements.txt
          action: rebuild
        - path: ./server
          target: /app
          action: sync



