version: '3.8'

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

